collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.07596687483601272
color:
  saturation: 0.44456522981636226
  brandStrength: 0.7559480564668775
  rhythmicContrast: 0.6525416488293558
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  lightness: 0.541012737667188
layout_spectrum: 0.8311235092114657
name: "Rob's random ramblings"
author:
  name: Rob Norton
  email: robnorton@gmail.com
