author:
  name: Rob Norton
  email: robnorton@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9862662917003036
  brandStrength: 0.5878136
  lightness: 0.4879057339858264
  brandColors:
    - '#131418'
    - '#FFFFFF'
    - '#4E4D4B'
    - '#8F9497'
    - '#B7BEC8'
  rhythmicContrast: 0.2547375159338117
typography_spectrum: 0.3691756
layout_spectrum: 0.9247312
name: Rob's random ramblings
